name: "PNPM installation"
description: "Install & Cache With PNPM"

inputs:
  version:
    description: "The version to use"
    required: false
    default: "9"

runs:
  using: "composite"
  steps:
    - name: "Install PNPM v${{ inputs.version }}"
      uses: pnpm/action-setup@v3
      with:
        version: ${{ inputs.version }}
        run_install: false

    - name: "Get PNPM Store Directory"
      shell: bash
      run: |
        echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV

    - name: "Setup PNPM Config"
      shell: bash
      run: pnpm config set store-dir ${{ inputs.cache }}

    - name: "Setup PNPM cache at '${{ env.STORE_PATH }}'"
      uses: actions/cache@v3
      with:
        path: ${{ inputs.cache }}
        key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
        restore-keys: |
          ${{ runner.os }}-pnpm-store-

    - name: "Install Dependencies"
      shell: bash
      run: pnpm install --frozen-lockfile
