name: Lint

env:
  NODE_VERSION: 20
  PNPM_VERSION: 9

on:
  push:
    branches:
      - "**"

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Cache turbo build setup
        uses: actions/cache@v4
        with:
          path: .turbo
          key: ${{ runner.os }}-turbo-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-turbo-

      - name: Setup Node.js v${{ env.NODE_VERSION }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          registry-url: https://registry.npmjs.org

      - name: Install & Audit PNPM
        uses: ./.github/actions/pnpm
        with:
          version: ${{ env.PNPM_VERSION }}

      - name: Lint project
        run: pnpm run lint && pnpm run build
