name: Pre-release CI

on:
  push:
    branches:
      - "dev"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with:
          version: 7
      - uses: actions/setup-node@v3
        with:
          node-version: 17.x
          cache: "pnpm"

      - run: pnpm install --frozen-lockfile
      - run: pnpm run build
