name: Releases

env:
  NODE_VERSION: 20
  PNPM_CACHE_FOLDER: .pnpm-store
  PNPM_VERSION: 9

on:
  workflow_run:
    workflows: [Lint]
    branches: [master]
    types: [completed]

concurrency: ${{ github.workflow }}-${{ github.ref }}

permissions:
  contents: write
  pull-requests: write

jobs:
  release:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository Workflow
        uses: actions/checkout@v4

      - name: Cache turbo build setup
        uses: actions/cache@v4
        with:
          path: .turbo
          key: ${{ runner.os }}-turbo-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-turbo-

      - name: Setup Node.js v${{ env.NODE_VERSION }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          registry-url: https://registry.npmjs.org

      - name: Install & Audit PNPM
        uses: ./.github/actions/pnpm
        with:
          cache: ${{ env.PNPM_CACHE_FOLDER }}
          version: ${{ env.PNPM_VERSION }}

      - name: Create Release Pull Request & Release
        uses: changesets/action@v1
        with:
          commit: chore(version) upgrade packages
          title: chore(version) upgrade packages
          publish: pnpm run release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
