name: Releases

on:
  workflow_run:
    workflows: [Lint]
    branches: [master]
    types: [completed]

concurrency: ${{ github.workflow }}-${{ github.ref }}

permissions:
  contents: write
  pull-requests: write

jobs:
  release:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository Workflow
        uses: actions/checkout@v4

      - name: Cache turbo build setup
        uses: actions/cache@v4
        with:
          path: .turbo
          key: ${{ runner.os }}-turbo-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-turbo-

      - name: "Install PNPM v${{ vars.PNPM_VERSION }}"
        uses: pnpm/action-setup@v4
        with:
          version: ${{ vars.PNPM_VERSION }}
          run_install: false

      - name: Setup Node.js v${{ vars.NODE_VERSION }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ vars.NODE_VERSION }}
          registry-url: https://registry.npmjs.org
          cache: "pnpm"

      - name: "Install Dependencies"
        shell: bash
        run: pnpm install --frozen-lockfile

      - name: Create Release Pull Request & Release
        uses: changesets/action@v1
        with:
          commit: "chore(version): upgrade packages"
          title: "chore(version): upgrade packages"
          publish: pnpm run release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
